name: Pull Request on Release Branch Push
on:
  push:
    branches:
      - 'release/**'
jobs:
  auto-pull-request:
    name: Release Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Check Readme Exists
        id: check_readme_exists
        uses: andstor/file-existence-action@v1
        with:
          files: "README.md"
      
      - name: Create Pull Request
        id: create_pull_request
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "release/"
          PULL_REQUEST_BRANCH: "master"
